### ISSUE TITLE
Sidebar cart only works after prod build

### ISSUE THREAD

**Issue by lnehlsen** [jaredkc/shopify-starter-theme#9]
Hello everyone,

I just started to use this very good template and currently experience an issue. The sidebar cart only works after "npm run prod:build" and not with after doing "watch:assets". The reason is that the js file starting with the name "vendors..." gets an error 404 after clicking on the cart.
Is this caused because of my bad webpack knowledge or is there something wrong with the code?

Best regards :)

**Comment by jaredkc** [comment]
Hello @lnehlsen. Are you running `watch:theme` at the same time?

**Comment by lnehlsen** [comment]
Thank you for your answer. Yes, I'm executing both at the same time. I found out that it works then I first execute "watch:assets" and then "watch:theme" afterwards.
I also want to say a big thank you for making this open source. It saved me so much time and is exactly what I needed! :)

**Comment by jaredkc** [comment]
I just took a quick look and confirmed that this is not working with `watch` commands. It appears to be a new issue with the `/* webpackChunkName: "app-cart-init" */` comment in `open-cart.js`. I don't have time to fix it this week. I'll update here when I can get to it.

**Comment by lnehlsen** [comment]
Thank you 😊

**Comment by lnehlsen** [comment]
Found out that it works when shorten the filename. For some reason "theme watch" doesn't push it with the long name. For me it's working when changing in webpack config 
"chunkFilename: '[name].[chunkhash:5].bundle.js' " 
to
"chunkFilename: '[chunkhash:5].bundle.js' "

**Comment by jaredkc** [comment]
Great find! Thanks for letting me know @lnehlsen
